name: aipolitician
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3
  - numpy>=1.26.0
  - pytorch>=2.0.0
  - tqdm=4.66.1
  - pip:
    - requests==2.31.0
    - beautifulsoup4==4.12.2
    - lxml==5.3.2
    - trafilatura==2.0.0
    - feedparser==6.0.10
    - python-dateutil>=2.9.0.post0
    - wikipedia==1.4.0
    - selenium==4.31.0
    - webdriver-manager==4.0.2
    - justext==3.0.2
    - htmldate==1.9.3
    - courlan==1.3.2
    - spacy>=3.5.0
    - nltk==3.8.1
    - newspaper3k==0.2.8
    - dateparser==1.2.1
    - transformers>=4.37.2
    - chromadb==0.4.18
    - sentence-transformers==2.2.2
    - typing-extensions>=4.5.0 